added Trivy & SonarQube to actions

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -75,38 +75,49 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
 
-      - name: Login to DockerHub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_TOKEN }}
+      - name: Build Docker Image
+        id: build
+        run: |
+          docker build -t ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ github.run_id }} -f src/product-catalog/Dockerfile src/product-catalog
 
-      - name: Build and Push Docker Image
-        id: buildpush
-        uses: docker/build-push-action@v6
-        with:
-          context: src/product-catalog
-          file: src/product-catalog/Dockerfile
-          push: true
-          tags: ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ github.run_id }}
-
-      # Scan the built Docker image with Trivy.
+      # Scan the built Docker image with Trivy BEFORE pushing.
       - name: Scan Docker Image with Trivy
+        id: trivy_scan
         uses: aquasecurity/trivy-action@master
         with:
           image-ref: ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ github.run_id }}
           severity: 'HIGH,CRITICAL'
           format: 'table'
-        # If vulnerabilities are found, this step will fail and prevent further steps.
+
+      # Stop the workflow if vulnerabilities are found.
+      - name: Fail If Vulnerabilities Are Found
+        if: failure()
+        run: |
+          echo "Trivy scan detected vulnerabilities. Failing the build."
+          exit 1
+
+      # Only push the image if the Trivy scan passes (i.e., no vulnerabilities found).
+      - name: Login to DockerHub
+        if: success()
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_TOKEN }}
+
+      - name: Push Docker Image
+        if: success()
+        run: |
+          docker push ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ github.run_id }}
 
   updatek8s:
     runs-on: ubuntu-latest
     needs: docker
+    if: success()  # Only execute if Docker image was successfully built and pushed
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4
         with:
-          token: ${{ secrets.GITHUB_TOKEN }}
+          token: ${{ secrets.GITHUB_TOKEN}}
 
       - name: Update Kubernetes Manifest
         run: |
